version: '3.9'
services:
  db:
    image: postgres:15
    container_name: mizan-db
    environment:
      POSTGRES_DB: mizan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dnd100
    ports:
      - "5432:5432"

  app:
    image: mizan-app
    container_name: mizan-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mizan
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dnd100
    depends_on:
      - db
