spring.application.name=Mizan
#DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/mizan
spring.datasource.username=postgres
spring.datasource.password=dnd100

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

#Spring Security Configuration
spring.security.user.name=farouk
spring.security.user.password=1234
